/-
  Copyright Strata Contributors

  SPDX-License-Identifier: Apache-2.0 OR MIT
-/

import Strata.Languages.Core.Verifier

/-! # Test: WF procedures survive FilterProcedures under selective verification

Ensures that the wf procedures generated by `PrecondElim` are not
removed by `FilterProcedures`.
-/

namespace Strata

def noFilterWFPgm :=
#strata
program Core;

procedure P(a : int, b : int) returns (r : int)
spec {
  requires [b_nonzero]: (b != 0);
  ensures [result_ok]: (r == a / b);
}
{
  r := a / b;
};

#end

-- Selectively verify only P. The WF procedure P$$wf must survive filtering.
/--
info:
Obligation: P_post_result_ok_calls_Int.SafeDiv_0
Property: assert
Result: ✅ pass

Obligation: set_r_calls_Int.SafeDiv_0
Property: assert
Result: ✅ pass

Obligation: result_ok
Property: assert
Result: ✅ pass
-/
#guard_msgs in
#eval verify noFilterWFPgm
        (options := Options.quiet)
        (proceduresToVerify := some ["P"])

-- Don't verify P, and don't produce a procedure for the contract
/-- info: -/
#guard_msgs in
#eval verify noFilterWFPgm
        (options := Options.quiet)
        (proceduresToVerify := some [])

end Strata
