/-
  Copyright Strata Contributors

  SPDX-License-Identifier: Apache-2.0 OR MIT
-/
module

meta import Strata.SimpleAPI
import Strata.Languages.Python.PythonDialect
meta import StrataTest.Util.Python

/-! ## Tests for directory-based pySpecsDir

Verifies that `pySpecsDir` correctly discovers, translates, and writes
PySpec Ion files for a directory of Python modules.
-/

namespace Strata.Python.Specs.PySpecsDirTest

open Strata (pySpecsDir pySpecOutputPath)

private meta def testDir : System.FilePath :=
  "StrataTestExtra/Languages/Python/Specs/pyspecs_dir_test"

/-- Check that a file exists at the given path. -/
private meta def fileExists (path : System.FilePath) : IO Bool := do
  match ← path.metadata |>.toBaseIO with
  | .ok md => pure (md.type == .file)
  | .error _ => pure false

-- ============================================================
-- Test: full directory scan produces expected output files
-- ============================================================

private meta def testFullDirectory : IO Unit := withPython fun pythonCmd => do
  IO.FS.withTempFile fun _handle dialectFile => do
    IO.FS.writeBinFile dialectFile Strata.Python.Python.toIon
    IO.FS.withTempDir fun outDir => do
      -- broken.py has a duplicate class, so pySpecsDir will report a failure.
      -- But continue-on-error means the good modules should still be translated.
      let _r ← pySpecsDir testDir outDir dialectFile
        (warningOutput := .none)
        (pythonCmd := toString pythonCmd) |>.toBaseIO

      -- Check expected output files exist (all except broken)
      let expectedFiles := #[
        "standalone.pyspec.st.ion",
        "testpkg/__init__.pyspec.st.ion",
        "testpkg/helper.pyspec.st.ion",
        "testpkg/consumer.pyspec.st.ion"
      ]
      let mut missing := #[]
      for f in expectedFiles do
        if !(← fileExists (outDir / f)) then
          missing := missing.push f
      if missing.size > 0 then
        -- List what actually exists for debugging
        let actual ← IO.Process.output {
          cmd := "find", args := #[outDir.toString, "-name", "*.ion", "-type", "f"]
        }
        throw <| IO.userError s!"Missing output files: {missing.toList}\nActual files:\n{actual.stdout}"

-- ============================================================
-- Test: --module flag filters to specific modules
-- ============================================================

private meta def testModuleFilter : IO Unit := withPython fun pythonCmd => do
  IO.FS.withTempFile fun _handle dialectFile => do
    IO.FS.writeBinFile dialectFile Strata.Python.Python.toIon
    IO.FS.withTempDir fun outDir => do
      let r ← pySpecsDir testDir outDir dialectFile
        (modules := #["standalone"])
        (warningOutput := .none)
        (pythonCmd := toString pythonCmd) |>.toBaseIO
      match r with
      | .error msg => throw <| IO.userError s!"pySpecsDir --module failed: {msg}"
      | .ok () => pure ()

      -- Only standalone should be translated (plus any cached imports)
      if !(← fileExists (outDir / "standalone.pyspec.st.ion")) then
        throw <| IO.userError "Expected standalone.pyspec.st.ion but not found"
      -- testpkg should NOT be directly translated (it may appear as a cached import)
      if ← fileExists (outDir / "testpkg/__init__.pyspec.st.ion") then
        throw <| IO.userError "testpkg/__init__.pyspec.st.ion should not be generated by --module standalone"

-- ============================================================
-- Test: --module with package name resolves __init__.py
-- ============================================================

private meta def testModulePackage : IO Unit := withPython fun pythonCmd => do
  IO.FS.withTempFile fun _handle dialectFile => do
    IO.FS.writeBinFile dialectFile Strata.Python.Python.toIon
    IO.FS.withTempDir fun outDir => do
      let r ← pySpecsDir testDir outDir dialectFile
        (modules := #["testpkg"])
        (warningOutput := .none)
        (pythonCmd := toString pythonCmd) |>.toBaseIO
      match r with
      | .error msg => throw <| IO.userError s!"pySpecsDir --module testpkg failed: {msg}"
      | .ok () => pure ()

      if !(← fileExists (outDir / "testpkg/__init__.pyspec.st.ion")) then
        throw <| IO.userError "Expected testpkg/__init__.pyspec.st.ion but not found"

-- ============================================================
-- Test: relative import inside package subdirectory resolves
-- correctly (from . import helper in a non-__init__ file)
-- ============================================================

private meta def testSubdirRelativeImport : IO Unit := withPython fun pythonCmd => do
  IO.FS.withTempFile fun _handle dialectFile => do
    IO.FS.writeBinFile dialectFile Strata.Python.Python.toIon
    IO.FS.withTempDir fun outDir => do
      let r ← pySpecsDir testDir outDir dialectFile
        (modules := #["testpkg.consumer"])
        (warningOutput := .none)
        (pythonCmd := toString pythonCmd) |>.toBaseIO
      match r with
      | .error msg => throw <| IO.userError s!"pySpecsDir --module testpkg.consumer failed: {msg}"
      | .ok () => pure ()

      if !(← fileExists (outDir / "testpkg/consumer.pyspec.st.ion")) then
        throw <| IO.userError "Expected testpkg/consumer.pyspec.st.ion but not found"

-- ============================================================
-- Test: incremental - second run skips up-to-date files
-- ============================================================

private meta def testIncremental : IO Unit := withPython fun pythonCmd => do
  IO.FS.withTempFile fun _handle dialectFile => do
    IO.FS.writeBinFile dialectFile Strata.Python.Python.toIon
    IO.FS.withTempDir fun outDir => do
      -- First run
      match ← pySpecsDir testDir outDir dialectFile
        (modules := #["standalone"])
        (warningOutput := .none)
        (pythonCmd := toString pythonCmd) |>.toBaseIO with
      | .error msg => throw <| IO.userError s!"First run failed: {msg}"
      | .ok () => pure ()

      let outFile := outDir / "standalone.pyspec.st.ion"
      let .ok md1 ← outFile.metadata |>.toBaseIO
        | throw <| IO.userError "Output file missing after first run"
      let mtime1 := md1.modified

      -- Brief pause so filesystem timestamps differ
      IO.sleep 100

      -- Second run — should skip since output is newer
      match ← pySpecsDir testDir outDir dialectFile
        (modules := #["standalone"])
        (warningOutput := .none)
        (pythonCmd := toString pythonCmd) |>.toBaseIO with
      | .error msg => throw <| IO.userError s!"Second run failed: {msg}"
      | .ok () => pure ()

      let .ok md2 ← outFile.metadata |>.toBaseIO
        | throw <| IO.userError "Output file missing after second run"
      let mtime2 := md2.modified

      -- Timestamp should be unchanged (file was not rewritten)
      if mtime1 != mtime2 then
        throw <| IO.userError s!"Output was rewritten on second run (expected incremental skip)"

-- ============================================================
-- Test: error in one module doesn't prevent others
-- ============================================================

private meta def testContinueOnError : IO Unit := withPython fun pythonCmd => do
  IO.FS.withTempFile fun _handle dialectFile => do
    IO.FS.writeBinFile dialectFile Strata.Python.Python.toIon
    IO.FS.withTempDir fun outDir => do
      -- Translate both standalone (good) and broken (has duplicate class)
      let r ← pySpecsDir testDir outDir dialectFile
        (modules := #["standalone", "testpkg.broken"])
        (warningOutput := .none)
        (pythonCmd := toString pythonCmd) |>.toBaseIO
      -- Should fail (because broken module has an error)
      match r with
      | .ok () =>
        throw <| IO.userError "Expected failure due to broken module, but succeeded"
      | .error msg =>
        -- The good module should still have been translated
        if !(← fileExists (outDir / "standalone.pyspec.st.ion")) then
          throw <| IO.userError s!"standalone.pyspec.st.ion missing — error in broken module prevented other translations\nError: {msg}"
        -- Error message should mention the broken module
        if !(msg.splitOn "testpkg.broken").length != 1 then
          throw <| IO.userError s!"Error message doesn't mention testpkg.broken:\n{msg}"

-- ============================================================
-- Test: pySpecOutputPath
-- ============================================================

private meta def testOutputPath : IO Unit := do
  let check (src out file expected : String) : IO Unit := do
    match pySpecOutputPath src out file with
    | some p =>
      if p.toString != expected then
        throw <| IO.userError s!"pySpecOutputPath {src} {out} {file}: expected {expected}, got {p}"
    | none =>
      throw <| IO.userError s!"pySpecOutputPath {src} {out} {file}: expected {expected}, got none"
  check "inputs" "out" "inputs/foo.py" "out/foo.pyspec.st.ion"
  check "inputs" "out" "inputs/pkg/__init__.py" "out/pkg/__init__.pyspec.st.ion"
  check "inputs" "out" "inputs/pkg/mod.py" "out/pkg/mod.pyspec.st.ion"

-- ============================================================
-- Runner
-- ============================================================

private meta def runAllTests : IO Unit := do
  testOutputPath
  testFullDirectory
  testModuleFilter
  testModulePackage
  testSubdirRelativeImport
  testIncremental
  testContinueOnError

#guard_msgs in
#eval runAllTests

end Strata.Python.Specs.PySpecsDirTest
