name: Label merge conflicts

on:
  push:
    branches: [main]
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  label-conflicts:
    runs-on: ubuntu-slim
    steps:
      - uses: prince-chrismc/label-merge-conflicts-action@21e6705eaa6aab66e4e486279389c8e3e4c465b7 # v3
        with:
          conflict_label_name: "Git conflicts"
          github_token: ${{ secrets.GITHUB_TOKEN }}
